version: '3.8'

services:
  postgres:
    build:
      context: .
      target: db
    environment:
      POSTGRES_USER: lottobueno
      POSTGRES_PASSWORD: lottobueno
      POSTGRES_DB: lottobueno
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5547:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lottobueno -h localhost"]
      interval: 10s
      retries: 5
    networks:
      - lotto-bueno-network

  redis:
    image: redis:latest
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - lotto-bueno-network

  app:
    build:
      context: .
      target: app
    environment:
      DATABASE_URL: "postgresql://lottobueno:lottobueno@postgres:5432/lottobueno"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8003:8000"
    networks:
      - lotto-bueno-network

volumes:
  pgdata:
  redis-data:

networks:
  lotto-bueno-network:
