version: '3.8'

services:
  db:
    build: .
    environment:
      POSTGRES_DB: lottobueno
      POSTGRES_USER: lottobueno
      POSTGRES_PASSWORD: lottobueno
    volumes:
      - ./lottobueno_backup.dump:/docker-entrypoint-initdb.d/lottobueno_backup.dump
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - db-data:/var/lib/postgresql/data
    ports:
      - "5532:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lottobueno"]
      interval: 10s
      retries: 5
    entrypoint: ["/docker-entrypoint-initdb.d/init-db.sh"]

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      DATABASE_URL: "postgresql://lottobueno:lottobueno@db:5432/lottobueno"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db-data:
  redis-data:
