version: '3.8'

services:
  postgres:
    build:
      context: .
      target: db
    environment:
      POSTGRES_USER: lottobueno
      POSTGRES_PASSWORD: lottobueno
      POSTGRES_DB: lottobueno
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./lottobueno_backup.dump:/docker-entrypoint-initdb.d/lottobueno_backup.dump
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./wait-for-it.sh:/docker-entrypoint-initdb.d/wait-for-it.sh
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5547:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lottobueno -h postgres"]
      interval: 10s
      retries: 5
    networks:
      - lotto-bueno-network

  redis:
    image: redis:latest
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - lotto-bueno-network

  app:
    build:
      context: .
      target: app
    environment:
      DATABASE_URL: "postgresql://lottobueno:lottobueno@postgres:5432/lottobueno"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - lotto-bueno-network

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "3000:3000"
    environment:
      # Solo la URL base, las rutas completas se construirán en el frontend
      NEXT_PUBLIC_API_URL: "https://applottobueno.com/"
    networks:
      - lotto-bueno-network
    depends_on:
      - app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/www/certbot:/var/www/certbot
    networks:
      - lotto-bueno-network
    depends_on:
      - app

volumes:
  pgdata:
  redis-data:

networks:
  lotto-bueno-network:
